name: CI/CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:

  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install project dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm test

      - name: Upload Website Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  cd:
    name: Continuous Delivery

    needs: ci

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
